language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - py.test


env:
  - secure: "WHAXTGjW8qD2hODpfhHvJ3fW8zeOhOLy+g0/HmIve6eh9D4nUhv5drn96vtNf4GpwgL4KI+u0wSHkOIlspNObZCOQLyZ0tnZM/FuRDrGW8PDab6lkZJyDZBx9yJqucat4w6AmFKlk+yJf6i4pfL83cLhRI8xJE4i+wwM08HgH+Q0CgMJh1m3vhvHWbmx5ea9Bv+/m8GRFsZy9AwBbsAGJT97h40roZ+7xPuSwQq/oCyYQZbVdfgqnT6hCUWnda7yf60RKEu91K7NTNb6NRKAM3cUvr0mPhyRTFbQbEZ4vn1hd2C75+chNJUoGjZ1rlZm0QSegoZfZgxdmlAMdzrmxjx5P31T+3inFyWafkVQo/oDd8H56CswGs2AoYjOfWgjYPydmUQTpAmBXKZ3FsSQG7sJg4QBJfmhUss32DipnasQ+Si6dIOojRx/lwPIyNWXv8tp6vVIZGH8BlPoDLvFncct7BtPeT55pyRzHtrAttVgVSt+9Ka7c/01Xw9XRjk95xrs6hh3feI51dO0Dk1Asw+L4/BnQ3nQRDffB6EAG9IzFlT0NXvdyhRi7gLUd05JclN5FqekOgKT50Tf/iaAObGpwXZfUaT/43bmuPQEt7mfK6z3CIw4emP7k6kFXUUoL6iFo5bu7XdDr5d+zC54p6JHdMMzlCxvF5gta0Kan+Q="
  - secure: "Rh23HOJws4XqG/ao44EKFM5USp3AoPsK2guJt8J9syjK8sCxdb9kvD6x0OK51yeaigpkN0PUMEojzYQHU80dRnzdRe9Mk2Y5p9ScKMhUTkI+56/Uub176jjJLCEo7olCMXjmVVKVNs4TE8mUAjvZKvGellFXoGi9sv7LG3D+e2zJHDA9p3zm6D+9TKbYynOCri0tUpvrRZbpdoukQ4CmqnTsC31X1fCSDy+4uLZsy3K0Y3GpluJsHCh7Sf3WBtxFLoGH5PbLYd5HWSiLUpyrE/FXuehsLEYIy3aDc7RfOdSoP5AcAC5UM99x4/QFQ+D7ycCLwp89TEzNq1Be1yfm5F7/qvgnz55FUfIuXkKfCB9ePScL9DqkKDr8vEdpy7EfSBhvANazRnldvaHeGZo9KK9ZLQ8mahSa33fAXrU2NJmYO5B0UgXunsOEiEsmnSNg6sejLZY04aW11NMW0qjCTIrFOdcyKXRhe5AsE/UheAN8XwMFHTFH/MkEz/3B9S3O4uP2arSRHJ+qY/mPuGIoWM+IT+X5mirGrK0rGphwuJR+PRaWe6L0gz7da8YfPA40WjeUlYt+fJHBj4DpwPcp+g7dstA8Kurh3ZBXv6rqmC96qZj1l4wVdknvlLpD0tv8Nkj2xNhhFhOhbnRNqmoBrAkY1rIg2ZnvEUvwvIWYcFc="
