language: python

python:
  - "2.7"

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - auth-cli -u $IOTLAB_USER -p $IOTLAB_PASS
  - tests/setup_ssh_key.sh

script:
  - py.test tests/ api_tests/


env:
 global:
  - secure: "hZAXwBYH+rBEn9WlEwroPKe93JlSSwHJqiJPllR30sjtmyFhhQ6v7Pmgq6Ut6tTPLpanPWtIkkHmfj1yKraoZDrOysjlrVMYjLNbPmEnuCFkj0buPMc+u2MO/5EDnSEdcb+QivDUuDsIKvTvTtoY+Tga+WnCYVMk4aZWl0S6tN0NSBXpv9LwW4HFmskDqA48YSTx53/fM7SGGO82iKa6eAjnbjqK/JCQEaqYH1wgEgUaHfzFb8rQ3UHN/715Wu9q1FesOIdyYRyYUt9DkPDzhd7RNK6LkshzIk/MhmN0CeDnMXFqURy6Bmnf7gLq6jgMdfC5ptsYEn+zyNHBZKy+j508iXjJKFRWkXygrcLTU/Zi47A4yQhYBS6DqK2hcFecQR/LuVx9Nmdi45W+zq6N0P43sBtllOxnHliulU7MC4zpKUEnxaYtZ3sKuUMuNFqBdyG5uabuWfO4odUOOKySc5FVCyGSJQWdCDNIdCx1lE7SZxQ3PdBgs5bno7r9uY0Fl3HAG8QEcoYNoCv65uyrR9Vpv+1w2gQdGRNDyoHiJBFznkP/ESPzvAZpjFf8Tr033s2GYQVWwqIq1oL+KIfsnpTfp/NZyWouTRpxq7ckBLcTBnpZiU/5VDgXij4qyzyPkyus1l/bijyjlFOwuYLaw6El2NIlg4IoFC2VdSAO+ek="
  - secure: "Pf37TEHSomsJDGGS/E/m8K/yb+dokRMky99oxeDyTcIvL+QZSniBsWbnUfsOy0RP9p9flDyGGlnZES/Osf5FMKPx2q01AzKBvUQBmrWsy8dKYrZ7An+aErS/8BfGA3M6hmcIRXrfxS31sWPepcT8qeOLRiH7CirbSQb92EENOKH1fga1QVj2jia8NKVhLBRv2NqYNXm2y3F3RybPt8y+K7z7Wzdkgjfl1GzALfDl1HeAwvxnA/qNnqunoy2M7n80BM+LUdinnVKe/x9jXn/EVQ3mVfmS5wuOyi4gWzn8RpHUGjm7v58RW0z5ttZI80GN8nCMrkwMaO4E0NgXEIii1ZrXkiRObspj5p7lrSCbvbJe8TDGUpNQ6aTUo4RjFu//Ff8iSF9eBnnNJKI9sftq7qRtEVtuo0hYVe8zyRAU9RbQe2dSdI3jgjHLboFF9SC9AGkgEkujRPSi5e11NvU7ltY1kqewDspskBy/tXUnLnWEUua3dkQhh8GDS1D9k5YnabQMbO/WlXvnJ6QEE/xdkeJoUUa+I9a5SiRCl/n/0z+vExldjJ//2Kgy+V6OuV6sOEgagsgdSjJcdzrHmvN1iasNrzgAf1bUTTocIAc9H964HyQWzLz31qamUZJbF1N+RMCbzQn7fSD+QqRKsSp2etHj1iFDfZ8jD+fuhyxyCss="
