language: python

python:
  - "2.7"

install:
  - pip install pytest --upgrade
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - auth-cli -u $IOTLAB_USER -p $IOTLAB_PASS
  - tests/setup_ssh_key.sh

script:
  - py.test tests/ api_tests/


env:
 global:
  - secure: "d3uI5F3vt2mNvzll5sgEl4C32X5BRDLK4eWYGrd/13jkpjVTXc9hDn0K1h0XJU7Q9AhdUCVskcPoGyIYEWzLxgo2uSzBzPXl6HYyH+TOebpDU3uBK5pC/2uGDmxakUfK6hq48te330/q0CWub1JDU4WAJbOTWwZOl4tK8VhFW++xHJvhLsP8Vz2yXwPhV6C9qOOzNA/L9aUz0Ovxl7L/0/AJ0SzLURrKmDDJuYPY72IX8GZO7BMm/YFCCXZMJx0xUxa5Ktu3otkvwMdfMFYd90YjT/qHd9MIyUJYyXrnvF6Xv9LNS58I8mwGik1VSu1dSKQvVitLdlzBbHVNOPuZmowUhGBl4nJRgOHsq5GU1/JHdC2eRvCJp92NFFhZ3va/SYrT9D8MD5xME68JPLj7WqZ05WDNPSmV6p5uJDPMcj5rEBoux1ij9/7ReanPq7aw6pJpzxK0OYwNTktKS3ES6EaQIkzRkkEEt+Dd/qm2qPOpif7NJPkHgxgvQ3J72pf/SrE0L8uI5x/CTmzBv+7lFYmtEIltbTB+ov/QRqNQojBYnGH86NA184ggKb4jF+Owf1MMIgK4XFr4SSao8iWxT/CAQnmFuaQK1a4j+qucLEoSjlfHhVrl6BeYb8jyJ12vC2TvuVjKSR5aA2KgN+yVAZXuSlqPjCr6xfMywPx7/pU="
  - secure: "psMoAcJNGFSM6eYUYP9eHttgYkRpEhlhzaplqv2V4bHkBNQ5jm3TNrYcw99BaXh5jfYKw3xMGZw5umO5YHmPrZQiJdQw4r1YovpGzjCOs+Yhc7Qi4QbT7N6WR4cOImGc3VdKIE388+jLI+JFbCwiWzdgIPzsZZdUFdmYJ6ByEib+r/bawWYYkwlog3guwWjptYea8vHnhQy5eKnvvZ36xQYsMFQDQZZeWQBBZU2fHlrAIvZCu5/6nzONC/M7TRCPCUrzczTBXJANeoM1Ac4VRoWwpYluVtkpM1rT8n6sw/EakZ8PDEVDYqjet/LYKXn9+6tN2YtdO4mPzJ3TIEIKE8gFSsgpbky83uZxDsHZ20GW7KyLDBQKHZNIiVrIQVrdc5kXvANoRwW5OyzH9U0pzii+iV8h9jC72oz2E+2O6Cz4qxJrd/MfsOJoQrH1PmrLMkWeC8FI4oCzIWvhUL9km7bkFmj6c55UutGb1/arYRAomSra7kodlXpazlnBUVyYHbef7S5f769IFutlx7VnrnmCF+BLTT4g/fo49o88ZJL9k64LPpuMBk6Twxpj15g2KsFD0sSQy6BKPEIvCZgDsuLwWNhuIjzHWl0O8BBBz2ZZvSuftzJXhuE5CrfFX/wI4u+G151YORQH6ypncZT1DHBR+d4/4+R9CX+Q4uIlaWU="
